## init stuff

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
%cd gdrive/My\ Drive/Colab\ Notebooks/text-gen

/content/gdrive/My Drive/Colab Notebooks/text-gen


In [0]:
# !git remote add origin https://jcrangel:pass@github.com/jcrangel/text-gen.git

In [0]:
!git config --global user.email "jcrangel@protonmail.com"
!git config --global user.name ">< rangel"

In [57]:
!git commit -m "data and models added"


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@3b8eac2bc568.(none)')


In [164]:
# !git commit -m "all"

[master 016ba86] all
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite word_gen_emb_pretrained.ipynb (95%)


In [0]:
# !git remote remove origin

In [58]:
!git push origin master

Everything up-to-date


In [0]:
#Initial config
# chekpoint file name
filepath_checkp="models/bidi_model_acc048.hdf5"
#model file name
model_name = 'model.h5'

#text input file name
in_filename = 'data/fables_aesop.txt'

#output text sequence filename
out_filename = 'data/fables_aesop_sequences.txt'

#
glove_vect_file = 'data/glove.6B.50d.txt'

In [0]:
%load_ext autoreload
%autoreload 2
from utils import *

## Process text

In [5]:

# load document

doc = load_doc(in_filename)
print(doc[:200])

# clean document
tokens = clean_doc(doc)
print(tokens[:200])
print('Total Tokens: %d' % len(tokens))
print('Unique Tokens: %d' % len(set(tokens)))

# organize into sequences of tokens
length = 50 + 1
sequences = list()
for i in range(length, len(tokens)):
	# select sequence of tokens
	seq = tokens[i-length:i]
	# convert into a line
	line = ' '.join(seq)
	# store
	sequences.append(line)
print('Total Sequences: %d' % len(sequences))

# save sequences to file
save_doc(sequences, out_filename)

THE WOLF AND THE LAMB


ONE day a Wolf and a Lamb happened to come at the same time to drink
from a brook that ran down the side of the mountain.

The Wolf wished very much to eat the Lamb, but meetin
['the', 'wolf', 'and', 'the', 'lamb', 'one', 'day', 'a', 'wolf', 'and', 'a', 'lamb', 'happened', 'to', 'come', 'at', 'the', 'same', 'time', 'to', 'drink', 'from', 'a', 'brook', 'that', 'ran', 'down', 'the', 'side', 'of', 'the', 'mountain', 'the', 'wolf', 'wished', 'very', 'much', 'to', 'eat', 'the', 'lamb', 'but', 'meeting', 'her', 'as', 'he', 'did', 'face', 'to', 'face', 'he', 'thought', 'he', 'must', 'find', 'some', 'excuse', 'for', 'doing', 'so', 'so', 'he', 'began', 'by', 'trying', 'to', 'pick', 'a', 'quarrel', 'and', 'said', 'angrily', 'dare', 'you', 'come', 'to', 'my', 'brook', 'and', 'muddy', 'the', 'water', 'so', 'that', 'i', 'cannot', 'drink', 'it', 'what', 'do', 'you', 'the', 'lamb', 'very', 'much', 'alarmed', 'said', 'gently', 'do', 'not', 'see', 'how', 'it', 'can', 'be', 'that

## get training data

Read the vector from glove file

In [10]:
word_to_index, index_to_word, word_to_vec_map = read_glove_vecs(glove_vect_file)

Loading glove vecs . ... 


In [11]:
X1 = np.array(["funny lol", "lets play baseball", "food is ready for you"])
X1_indices = sentences_to_indices(X1,word_to_index, index_to_word, word_to_vec_map, max_len = 5)
print("X1 =", X1)
print("X1_indices =", X1_indices)

X1 = ['funny lol' 'lets play baseball' 'food is ready for you']
X1_indices = [[155345. 225122.      0.      0.      0.]
 [220930. 286375.  69714.      0.      0.]
 [151204. 192973. 302254. 151349. 394475.]]


In [0]:
# load
doc = load_doc(out_filename)
lines = doc.split('\n')
lines = np.array(lines)
length = 50 + 1


In [16]:
print(lines[:5])

['the wolf and the lamb one day a wolf and a lamb happened to come at the same time to drink from a brook that ran down the side of the mountain the wolf wished very much to eat the lamb but meeting her as he did face to face he'
 'wolf and the lamb one day a wolf and a lamb happened to come at the same time to drink from a brook that ran down the side of the mountain the wolf wished very much to eat the lamb but meeting her as he did face to face he thought'
 'and the lamb one day a wolf and a lamb happened to come at the same time to drink from a brook that ran down the side of the mountain the wolf wished very much to eat the lamb but meeting her as he did face to face he thought he'
 'the lamb one day a wolf and a lamb happened to come at the same time to drink from a brook that ran down the side of the mountain the wolf wished very much to eat the lamb but meeting her as he did face to face he thought he must'
 'lamb one day a wolf and a lamb happened to come at the same time to d

In [18]:
len(lines[5].split())

51

In [19]:
# integer encode sequences of words
#okenizer = Tokenizer()
#tokenizer.fit_on_texts(lines)

#array([   15,     1,   306, 10270,    28,     7,   363,   225,  4604,....])
sequences = sentences_to_indices(lines,word_to_index, index_to_word, word_to_vec_map, max_len = length)
# vocabulary size
vocab_size = len(word_to_index) + 1  
X, y = sequences[:,:-1], sequences[:,-1]
#y = to_categorical(y, num_classes=vocab_size) eats all memory use sparse_categorical_crossentropy
seq_length = X.shape[1]

famishing doesnt have index, new entry created
storkking doesnt have index, new entry created
grayear doesnt have index, new entry created
whitewhisker doesnt have index, new entry created
gayly doesnt have index, new entry created
unsuspicious doesnt have index, new entry created
capered doesnt have index, new entry created
selfimportance doesnt have index, new entry created
dainties doesnt have index, new entry created
manyfeathered doesnt have index, new entry created
oneeyed doesnt have index, new entry created
repine doesnt have index, new entry created
filberts doesnt have index, new entry created
illmannered doesnt have index, new entry created
cowhides doesnt have index, new entry created
fairtime doesnt have index, new entry created
wellproved doesnt have index, new entry created
dinnerless doesnt have index, new entry created
miry doesnt have index, new entry created
selfinterest doesnt have index, new entry created
evildisposed doesnt have index, new entry created
faultfindi

In [20]:
print(X.shape)
print(y.shape)
print(len(lines[30].split()))

(88749, 50)
(88749,)
51


In [21]:
word_to_index['mermaid']

241527

## Training phase

In [0]:
from numpy import array
from pickle import dump

In [23]:
from models import pretrained_embedding_layer
embedding_layer = pretrained_embedding_layer(word_to_vec_map, word_to_index)
print("weights[0][1][3] =", embedding_layer.get_weights()[0][1][3])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
weights[0][1][3] = -0.3403


In [0]:
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

In [0]:
from models import bidi_model
# define model
model = bidi_model(word_to_vec_map,word_to_index)
checkpoint = ModelCheckpoint(filepath_checkp, monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
# fit model
model.fit(X, y, batch_size=128, epochs=100, callbacks=callbacks_list)
# save the model to file
model.save(model_name)
# save the tokenizer

Reload and continue training

In [0]:
from tensorflow.keras.models import load_model

model = load_model(filepath_checkp)
checkpoint = ModelCheckpoint(filepath_checkp, monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
# fit model
model.fit(X, y, batch_size=128, epochs=100, callbacks=callbacks_list)

Train on 88749 samples
Epoch 1/100
88704/88749 [============================>.] - ETA: 0s - loss: 2.2813 - acc: 0.4530
Epoch 00001: acc improved from -inf to 0.45292, saving model to weights-improvement.hdf5
88749/88749 [==============================] - 300s 3ms/sample - loss: 2.2816 - acc: 0.4529
Epoch 2/100
88704/88749 [============================>.] - ETA: 0s - loss: 2.2676 - acc: 0.4569
Epoch 00002: acc improved from 0.45292 to 0.45687, saving model to weights-improvement.hdf5
88749/88749 [==============================] - 296s 3ms/sample - loss: 2.2679 - acc: 0.4569
Epoch 3/100
88704/88749 [============================>.] - ETA: 0s - loss: 2.2621 - acc: 0.4548
Epoch 00003: acc did not improve from 0.45687
88749/88749 [==============================] - 294s 3ms/sample - loss: 2.2623 - acc: 0.4548
Epoch 4/100
88704/88749 [============================>.] - ETA: 0s - loss: 2.2622 - acc: 0.4570
Epoch 00004: acc improved from 0.45687 to 0.45701, saving model to weights-improvement.hdf

KeyboardInterrupt: ignored

## Generate text sequence 

In [0]:
from utils import sample, generate_seq

In [0]:
# load cleaned text sequences
doc = load_doc(out_filename)
lines = doc.split('\n')
seq_length = len(lines[0].split()) - 1

# load the model
model = load_model(filepath_checkp)


In [27]:
# select a seed text
seed_text = lines[15]#lines[randint(0,len(lines))
sentences_to_indices(np.array([seed_text]),word_to_index, index_to_word, word_to_vec_map, max_len = length)

array([[ 62065., 357266., 316998., 359889., 360915., 129404., 154323.,
         43010.,  84884., 357212., 300216., 128527., 357266., 330916.,
        268046., 357266., 250836., 357266., 389245., 388590., 377946.,
        251645., 360915., 132701., 357266., 216334.,  87775., 239792.,
        177103.,  60665., 175199., 123517., 143869., 360915., 143869.,
        175199., 358464., 175199., 253767., 148427., 337259., 142467.,
        151349., 126981., 336114., 336114., 175199.,  71917.,  88126.,
        366274., 360915.]])

In [28]:
len(seed_text.split())

51

In [0]:

model = load_model(filepath_checkp)

In [32]:
print(seed_text)
# generate 30 new words
generated = generate_seq(model, word_to_index, index_to_word, word_to_vec_map, seed_text,length,30,temperature = 0.5)
print(generated)

at the same time to drink from a brook that ran down the side of the mountain the wolf wished very much to eat the lamb but meeting her as he did face to face he thought he must find some excuse for doing so so he began by trying to


/content/gdrive/My Drive/Colab Notebooks/text-gen/utils.py:114: RuntimeWarning: divide by zero encountered in log
  preds = np.log(preds) / temperature


the was not the him the beheld he meant find so of to the so he he snapped to trying to town ground cried small man had donkey and had


In [33]:
seed_text = 'the wolf was playing with his tail'
print(seed_text)
# generate 30 new words
generated = generate_seq(model, word_to_index, index_to_word, word_to_vec_map, seed_text,length,30,temperature=0)
print(generated)

the wolf was playing with his tail
him him him him him him him him him them him his him him him him him him him him him him him to to to to to to to
